language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t kushiester/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kushiester/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  application: 'rest-app'
  env: 'rest-app-env'
  bucket_name: '<S3 bucket Name>'
  bucket_path: 'rest-app'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'